### ISSUE TITLE
Participate in Hacktoberfest

### ISSUE THREAD

**Issue by importhuman** [Sahil-k1509/cmd_pokemon#12]
Can you please add the hacktoberfest topic to the repository? I realized that my PRs are not being counted and simply labelled as being for an ineligible repository. I would really appreciate it.

**Comment by Sahil-k1509** [comment]
I will add the hacktoberfest label but i would suggest you to contribute to some other repository if you are doing it just for the sake for hacktober. Anyway. Appreciate your contribution

**Comment by Sahil-k1509** [comment]
Also, A repository isn't marked with hacktoberfest label, only  issues can be marked. And this repo doesn't have that many issues created. You should check out repo with high issues to quickly do 4 eligible PR. I contributed to 'py-contributors', 'python-world', 'tessaract' and other organizations(not users).

**Comment by importhuman** [comment]
I started it for Hacktoberfest, but I really like it, so I'll work on it even if it doesn't count towards it. :)

**Comment by importhuman** [comment]
I did not see this message on GitHub, I only found this email now. Thank
you very much. Looking forward to contributing more, currently going
through codebase.
