### ISSUE TITLE
Add more pokemons in pokeworld.py

### ISSUE THREAD

**Issue by Sahil-k1509** [Sahil-k1509/cmd_pokemon#2]

**Comment by dangerstone** [comment]
Would love to contribute. What is your source for base stats?

**Comment by Sahil-k1509** [comment]
You can use pokemondb.com>pokedex or you can create your own stats. I am creating my own stats :p
Actually, this was not meant to be a open source project, it was just for my practice on OOPs.

**Comment by dangerstone** [comment]
Okay, i'll try to match the stats you've created then. :) Thanks for sharing! 
Is there anything else we should keep in mind while adding pokemon?

**Comment by Sahil-k1509** [comment]
Not really. if you are doing it for hacktober. Be quick, only two days are left. I will accept them :-)

**Comment by dangerstone** [comment]
Hey, my PR's are marked as "Ineligible" by hacktoberfest, because you've removed the "hacktoberfest"-topic from the repository. :(
Do you mind putting it back? Or alternatively labeling my PR's with "hacktoberfest-accepted".

**Comment by dangerstone** [comment]
Okay, turns out it won't make a difference. Thanks anyway!
