### ISSUE TITLE
Add more attacks in attacklist.py

### ISSUE THREAD

**Issue by Sahil-k1509** [Sahil-k1509/cmd_pokemon#3]

**Comment by importhuman** [comment]
Hello! I'd love to contribute to this issue and otherwise as well to the project. According to which generation are you planning to code the game?

**Comment by Sahil-k1509** [comment]
@importhuman I have focussed on indigo league(Gen 1), but it's okay if you introduce other gen pokemons as well

**Comment by importhuman** [comment]
I was looking at attacklist.py, and noticed that Dark and Steel types are already there (introduced in Gen 2), and there are many moves that were introduced in later generations. Also, the damage is not what the usual damage in the games is, do you want to update that? I'm assuming baseCount is PP?

**Comment by Sahil-k1509** [comment]
Yeah Base count is PP. Feel free to add the changes, I created my own experience, health and damage increase functions so I chose values that fit best for them.

**Comment by dangerstone** [comment]
How do you determine recoil?

**Comment by Sahil-k1509** [comment]
> How do you determine recoil?

If u have seen pokemon. Some attacks like bolttackle used to affect pikachu as well. Just adding recoils to those kind of attacks. Intensity of recoil is our choice as this is not a production game xD. 

Edit: This issue is closed. ImportHuman added 30-40 new attacks but didnt mention this issue

**Comment by dangerstone** [comment]
Hehe, okay cool! Just checking to see if it should match some value from the actual game. :)
