### ISSUE TITLE
Can't run main.py

### ISSUE THREAD

**Issue by importhuman** [Sahil-k1509/cmd_pokemon#6]
![Screenshot from 2020-10-01 19-30-31](https://user-images.githubusercontent.com/69148722/94819409-dab7b500-041c-11eb-8d33-ed1ec6f299ce.png)
I've installed the required packages, I'm still getting this error. Please assist.

**Comment by Sahil-k1509** [comment]
@importhuman Thanks for pointing out. 
Error: in line, chindigop6 = Pokemon('magikarp', chindigop5, level=0) <- It should have been chindigop6.
I fixed that please check. It's running on my local device now.
(Chindigo is short for Champion Indigo League)

**Comment by importhuman** [comment]
Works now, thanks!
